export const BASE_BATCH_SIZE = 100
export const BASE_PAGE_FRAME_COUNT = 200
export const BASE_PAGE_MAX_COUNT = 250;
export const BASE_PAGE_REFERENCE_LENGTH = 200;
export const BASE_LOCALITY_WINDOW_SIZE = 150
export const BASE_SIMULATION_SPEED = 19.6
export const BASE_MAX_PROCESS_SIZE = 10**2
export const BASE_PROCESSES_COUNT = 10
export const BASE_MIN_LOCALITY_PAGES = 50
export const BASE_MAX_LOCALITY_PAGES = 100


export const SLOW_PAGE_FRAME_COUNT = 30
export const SLOW_PAGE_MAX_COUNT = 6;
export const SLOW_PAGE_REFERENCE_LENGTH = 40;
export const SLOW_LOCALITY_WINDOW_SIZE = 100
export const SLOW_SIMULATION_SPEED = 1
export const SLOW_MAX_PROCESS_SIZE = 10**2
export const SLOW_PROCESSES_COUNT = 3
export const SLOW_MIN_LOCALITY_PAGES = 10
export const SLOW_MAX_LOCALITY_PAGES = 15

export const ZONE_TIME_WINDOW = 33
export const EPSILON = 10**-10